baseurl = "http://wpumacay.github.io/blog/"
title = "Wilbert Pumacay"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true
publishDir = "docs"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Wilbert Pumacay"
  info = "Robo/ML Developer"
  description = "Wilbert Pumacay's blog"
  keywords = "blog,robotics,learning"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/wpumacay/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/wpumacay7567/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"